spring:
  config:
    activate:
      on-profile: dev
server:
  email: suharbramar@gmail.com
  cluster:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3