spring:
  config:
    activate:
      on-profile: prod
server:
  email: suharbramar00@gmail.com
  cluster:
    - ip: 192.168.0.1
      path: /app1
    - ip: 192.168.0.2
      path: /app2
    - ip: 192.168.0.3
      path: /app3